package PanelMenu;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;



public class data_kendaraan extends javax.swing.JPanel {
private final Connection conn = koneksi.getKoneksi();
private DefaultTableModel tabmode;
    /**
     * Creates new form data_kendaraan
     */
    public data_kendaraan() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }
    
    protected void aktif(){
    tcari_kendaraan.requestFocus();
    }
    
    protected void kosong(){
    tcari_kendaraan.setText("");
    }
    
 protected void datatable() {
    Object[] kolom = {"Nama Pemilik", "Merk Kendaraan", "Nomor Polisi", "Tanggal Masuk", "Tanggal Selesai"};
    tabmode = new DefaultTableModel(null, kolom);
    String cariitem = tcari_kendaraan.getText();

    try {
        String sql = "SELECT u.nama AS nama_pemilik, k.merk AS merk_kendaraan, " +
                     "k.no_polisi, s.tanggal_masuk, s.tanggal_selesai " +
                     "FROM kendaraan k " +
                     "JOIN user u ON k.id_user = u.id_user " +
                     "JOIN servis s ON s.id_kendaraan = k.id_kendaraan " +
                     "WHERE u.nama LIKE '%" + cariitem + "%' " +
                     "OR k.merk LIKE '%" + cariitem + "%' " +
                     "OR k.no_polisi LIKE '%" + cariitem + "%' " +
                     "ORDER BY u.nama ASC";

        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString("nama_pemilik"),
                hasil.getString("merk_kendaraan"),
                hasil.getString("no_polisi"),
                hasil.getString("tanggal_masuk"),
                hasil.getString("tanggal_selesai")
            });
        }
        // ubah JTable kamu jadi nama lain supaya tidak bentrok dengan nama class
        tblkendaraan.setModel(tabmode);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e);
    }
}
// === METHOD UBAH DATA KENDARAAN ===
protected void ubahData() {
    int baris = tblkendaraan.getSelectedRow();
    if (baris == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah terlebih dahulu!");
        return;
    }

    String noPolisi = tblkendaraan.getValueAt(baris, 2).toString(); // kolom ke-3
    String merkBaru = JOptionPane.showInputDialog("Masukkan merk kendaraan baru:");
    if (merkBaru == null || merkBaru.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Merk tidak boleh kosong!");
        return;
    }

    try {
        String sql = "UPDATE kendaraan SET merk = ? WHERE no_polisi = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, merkBaru);
        pst.setString(2, noPolisi);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
        datatable(); // refresh tabel
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data gagal diubah: " + e);
    }
}

// === METHOD HAPUS DATA KENDARAAN ===
protected void hapusData() {
    int baris = tblkendaraan.getSelectedRow();
    if (baris == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus terlebih dahulu!");
        return;
    }

    String noPolisi = tblkendaraan.getValueAt(baris, 2).toString();

    int konfirmasi = JOptionPane.showConfirmDialog(null,
            "Apakah Anda yakin ingin menghapus data dengan No Polisi: " + noPolisi + " ?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            String sql = "DELETE FROM kendaraan WHERE no_polisi = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, noPolisi);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            datatable(); // refresh tabel
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus: " + e);
        }
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkendaraan = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tcari_kendaraan = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("DATA KENDARAAN");

        tblkendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Pemilik", "Nama Kendaraan", "Merk", "Nomor Polisi", "Tanggal Masuk"
            }
        ));
        jScrollPane1.setViewportView(tblkendaraan);

        jLabel6.setText("Cari Kendaraan");

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        bubah.setText("Ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tcari_kendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(bubah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcari_kendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bubah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        ubahData();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        
         hapusData();
    }//GEN-LAST:event_bhapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblkendaraan;
    private javax.swing.JTextField tcari_kendaraan;
    // End of variables declaration//GEN-END:variables
}
