/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainMenu;

import PanelMenu.*;
import java.awt.Color;

/**
 *
 * @author Mhd
 */
public class HalamanAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HalamanAdmin
     */
    public HalamanAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnkiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pndashboard = new javax.swing.JPanel();
        pnline1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btndashboard = new javax.swing.JLabel();
        pndatauser = new javax.swing.JPanel();
        pnline2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btndatauser = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pndatapelanggan = new javax.swing.JPanel();
        pnline3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btndatapelanggan = new javax.swing.JLabel();
        pndatasparepart = new javax.swing.JPanel();
        pnline4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btndatasparepart = new javax.swing.JLabel();
        pndatakendaraan = new javax.swing.JPanel();
        pnline5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btndatakendaraan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pntransaksiservis = new javax.swing.JPanel();
        pnline6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btntransaksiservis = new javax.swing.JLabel();
        pnlaporanservis = new javax.swing.JPanel();
        pnline7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnlaporanservis = new javax.swing.JLabel();
        pnlaporantransaksi = new javax.swing.JPanel();
        pnline8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnlaporantransaksi = new javax.swing.JLabel();
        pnlaporansparepart = new javax.swing.JPanel();
        pnline9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnlaporansparepart = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pnlogout = new javax.swing.JPanel();
        pnline10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();
        pnkanan = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        pnutama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnkiri.setBackground(new java.awt.Color(255, 255, 255));
        pnkiri.setForeground(new java.awt.Color(242, 242, 242));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DUA PUTRI MOTOR");

        pndashboard.setBackground(new java.awt.Color(255, 255, 255));

        pnline1.setBackground(new java.awt.Color(255, 255, 255));
        pnline1.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout pnline1Layout = new javax.swing.GroupLayout(pnline1);
        pnline1.setLayout(pnline1Layout);
        pnline1Layout.setHorizontalGroup(
            pnline1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnline1Layout.setVerticalGroup(
            pnline1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icondashboard.png"))); // NOI18N

        btndashboard.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btndashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btndashboard.setText("DASHBOARD");
        btndashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pndashboardLayout = new javax.swing.GroupLayout(pndashboard);
        pndashboard.setLayout(pndashboardLayout);
        pndashboardLayout.setHorizontalGroup(
            pndashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndashboardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pndashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pndashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        pndashboardLayout.setVerticalGroup(
            pndashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pndashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pndashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pndashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pndatauser.setBackground(new java.awt.Color(255, 255, 255));

        pnline2.setBackground(new java.awt.Color(255, 255, 255));
        pnline2.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout pnline2Layout = new javax.swing.GroupLayout(pnline2);
        pnline2.setLayout(pnline2Layout);
        pnline2Layout.setHorizontalGroup(
            pnline2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnline2Layout.setVerticalGroup(
            pnline2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/data_pelanggan.png"))); // NOI18N

        btndatauser.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btndatauser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btndatauser.setText("DATA USER");
        btndatauser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndatauserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndatauserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndatauserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pndatauserLayout = new javax.swing.GroupLayout(pndatauser);
        pndatauser.setLayout(pndatauserLayout);
        pndatauserLayout.setHorizontalGroup(
            pndatauserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndatauserLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndatauser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pndatauserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pndatauserLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        pndatauserLayout.setVerticalGroup(
            pndatauserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndatauserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pndatauserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndatauser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pndatauserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pndatauserLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel7.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("MASTER DATA");

        pndatapelanggan.setBackground(new java.awt.Color(255, 255, 255));

        pnline3.setBackground(new java.awt.Color(255, 255, 255));
        pnline3.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout pnline3Layout = new javax.swing.GroupLayout(pnline3);
        pnline3.setLayout(pnline3Layout);
        pnline3Layout.setHorizontalGroup(
            pnline3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnline3Layout.setVerticalGroup(
            pnline3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/data_pelanggan.png"))); // NOI18N

        btndatapelanggan.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btndatapelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btndatapelanggan.setText("DATA PELANGGAN");
        btndatapelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndatapelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndatapelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndatapelangganMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pndatapelangganLayout = new javax.swing.GroupLayout(pndatapelanggan);
        pndatapelanggan.setLayout(pndatapelangganLayout);
        pndatapelangganLayout.setHorizontalGroup(
            pndatapelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndatapelangganLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndatapelanggan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pndatapelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pndatapelangganLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        pndatapelangganLayout.setVerticalGroup(
            pndatapelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndatapelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pndatapelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndatapelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pndatapelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pndatapelangganLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pndatasparepart.setBackground(new java.awt.Color(255, 255, 255));

        pnline4.setBackground(new java.awt.Color(255, 255, 255));
        pnline4.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout pnline4Layout = new javax.swing.GroupLayout(pnline4);
        pnline4.setLayout(pnline4Layout);
        pnline4Layout.setHorizontalGroup(
            pnline4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnline4Layout.setVerticalGroup(
            pnline4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/data_kendaraan.png"))); // NOI18N

        btndatasparepart.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btndatasparepart.setText("DATA SPAREPART");
        btndatasparepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndatasparepartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndatasparepartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndatasparepartMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pndatasparepartLayout = new javax.swing.GroupLayout(pndatasparepart);
        pndatasparepart.setLayout(pndatasparepartLayout);
        pndatasparepartLayout.setHorizontalGroup(
            pndatasparepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndatasparepartLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndatasparepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pndatasparepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pndatasparepartLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        pndatasparepartLayout.setVerticalGroup(
            pndatasparepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndatasparepartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pndatasparepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndatasparepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pndatasparepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pndatasparepartLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pndatakendaraan.setBackground(new java.awt.Color(255, 255, 255));

        pnline5.setBackground(new java.awt.Color(255, 255, 255));
        pnline5.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout pnline5Layout = new javax.swing.GroupLayout(pnline5);
        pnline5.setLayout(pnline5Layout);
        pnline5Layout.setHorizontalGroup(
            pnline5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnline5Layout.setVerticalGroup(
            pnline5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/data_kendaraan.png"))); // NOI18N

        btndatakendaraan.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btndatakendaraan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btndatakendaraan.setText("DATA KENDARAAN");
        btndatakendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndatakendaraanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndatakendaraanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndatakendaraanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pndatakendaraanLayout = new javax.swing.GroupLayout(pndatakendaraan);
        pndatakendaraan.setLayout(pndatakendaraanLayout);
        pndatakendaraanLayout.setHorizontalGroup(
            pndatakendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndatakendaraanLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndatakendaraan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pndatakendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pndatakendaraanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        pndatakendaraanLayout.setVerticalGroup(
            pndatakendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndatakendaraanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pndatakendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndatakendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pndatakendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pndatakendaraanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel14.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel14.setText("TRANSAKSI");

        pntransaksiservis.setBackground(new java.awt.Color(255, 255, 255));

        pnline6.setBackground(new java.awt.Color(255, 255, 255));
        pnline6.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout pnline6Layout = new javax.swing.GroupLayout(pnline6);
        pnline6.setLayout(pnline6Layout);
        pnline6Layout.setHorizontalGroup(
            pnline6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnline6Layout.setVerticalGroup(
            pnline6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksi.png"))); // NOI18N

        btntransaksiservis.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btntransaksiservis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btntransaksiservis.setText("SERVIS");
        btntransaksiservis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntransaksiservisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntransaksiservisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pntransaksiservisLayout = new javax.swing.GroupLayout(pntransaksiservis);
        pntransaksiservis.setLayout(pntransaksiservisLayout);
        pntransaksiservisLayout.setHorizontalGroup(
            pntransaksiservisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntransaksiservisLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntransaksiservis, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(pntransaksiservisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pntransaksiservisLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );
        pntransaksiservisLayout.setVerticalGroup(
            pntransaksiservisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntransaksiservisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pntransaksiservisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntransaksiservis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pntransaksiservisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pntransaksiservisLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlaporanservis.setBackground(new java.awt.Color(255, 255, 255));

        pnline7.setBackground(new java.awt.Color(255, 255, 255));
        pnline7.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout pnline7Layout = new javax.swing.GroupLayout(pnline7);
        pnline7.setLayout(pnline7Layout);
        pnline7Layout.setHorizontalGroup(
            pnline7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnline7Layout.setVerticalGroup(
            pnline7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan.png"))); // NOI18N

        btnlaporanservis.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnlaporanservis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlaporanservis.setText("SERVIS");
        btnlaporanservis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlaporanservisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlaporanservisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlaporanservisLayout = new javax.swing.GroupLayout(pnlaporanservis);
        pnlaporanservis.setLayout(pnlaporanservisLayout);
        pnlaporanservisLayout.setHorizontalGroup(
            pnlaporanservisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlaporanservisLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlaporanservis, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(pnlaporanservisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlaporanservisLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        pnlaporanservisLayout.setVerticalGroup(
            pnlaporanservisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlaporanservisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlaporanservisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlaporanservis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlaporanservisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlaporanservisLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlaporantransaksi.setBackground(new java.awt.Color(255, 255, 255));

        pnline8.setBackground(new java.awt.Color(255, 255, 255));
        pnline8.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout pnline8Layout = new javax.swing.GroupLayout(pnline8);
        pnline8.setLayout(pnline8Layout);
        pnline8Layout.setHorizontalGroup(
            pnline8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnline8Layout.setVerticalGroup(
            pnline8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan.png"))); // NOI18N

        btnlaporantransaksi.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnlaporantransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlaporantransaksi.setText("TRANSAKSI");
        btnlaporantransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlaporantransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlaporantransaksiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlaporantransaksiLayout = new javax.swing.GroupLayout(pnlaporantransaksi);
        pnlaporantransaksi.setLayout(pnlaporantransaksiLayout);
        pnlaporantransaksiLayout.setHorizontalGroup(
            pnlaporantransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlaporantransaksiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlaporantransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlaporantransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlaporantransaksiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        pnlaporantransaksiLayout.setVerticalGroup(
            pnlaporantransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlaporantransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlaporantransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlaporantransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlaporantransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlaporantransaksiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlaporansparepart.setBackground(new java.awt.Color(255, 255, 255));

        pnline9.setBackground(new java.awt.Color(255, 255, 255));
        pnline9.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout pnline9Layout = new javax.swing.GroupLayout(pnline9);
        pnline9.setLayout(pnline9Layout);
        pnline9Layout.setHorizontalGroup(
            pnline9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnline9Layout.setVerticalGroup(
            pnline9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan.png"))); // NOI18N

        btnlaporansparepart.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnlaporansparepart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlaporansparepart.setText("SPAREPART");
        btnlaporansparepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlaporansparepartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlaporansparepartMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlaporansparepartLayout = new javax.swing.GroupLayout(pnlaporansparepart);
        pnlaporansparepart.setLayout(pnlaporansparepartLayout);
        pnlaporansparepartLayout.setHorizontalGroup(
            pnlaporansparepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlaporansparepartLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlaporansparepart, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlaporansparepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlaporansparepartLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        pnlaporansparepartLayout.setVerticalGroup(
            pnlaporansparepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlaporansparepartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlaporansparepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlaporansparepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlaporansparepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlaporansparepartLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel23.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel23.setText("LAPORAN");

        pnlogout.setBackground(new java.awt.Color(255, 255, 255));

        pnline10.setBackground(new java.awt.Color(255, 255, 255));
        pnline10.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout pnline10Layout = new javax.swing.GroupLayout(pnline10);
        pnline10.setLayout(pnline10Layout);
        pnline10Layout.setHorizontalGroup(
            pnline10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnline10Layout.setVerticalGroup(
            pnline10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N

        btnlogout.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnlogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlogout.setText("LOGOUT");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlogoutLayout = new javax.swing.GroupLayout(pnlogout);
        pnlogout.setLayout(pnlogoutLayout);
        pnlogoutLayout.setHorizontalGroup(
            pnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlogoutLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlogoutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        pnlogoutLayout.setVerticalGroup(
            pnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlogoutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnline10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnkiriLayout = new javax.swing.GroupLayout(pnkiri);
        pnkiri.setLayout(pnkiriLayout);
        pnkiriLayout.setHorizontalGroup(
            pnkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnkiriLayout.createSequentialGroup()
                .addGroup(pnkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnkiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnkiriLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pntransaksiservis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pndatauser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pndashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pndatapelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pndatasparepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pndatakendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlaporanservis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlaporantransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlaporansparepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnkiriLayout.setVerticalGroup(
            pnkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnkiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(pndashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pndatauser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pndatapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pndatasparepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pndatakendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pntransaksiservis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlaporanservis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlaporantransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlaporansparepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(pnkiri, java.awt.BorderLayout.LINE_START);

        pnkanan.setLayout(new java.awt.BorderLayout());

        pnutama.setBackground(new java.awt.Color(255, 255, 255));
        pnutama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnkanan.add(panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnkanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndatauserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatauserMouseEntered
        pndatauser.setBackground(new Color(255, 255, 255));
        pnline2.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btndatauserMouseEntered

    private void btndatauserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatauserMouseExited
        pndatauser.setBackground(new Color(255, 255, 255));
        pnline2.setBackground(new Color(255, 255, 255)); 
    }//GEN-LAST:event_btndatauserMouseExited

    private void btndashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashboardMouseEntered
        pndashboard.setBackground(new Color(255, 255, 255));
        pnline1.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btndashboardMouseEntered

    private void btndashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashboardMouseExited
        pndashboard.setBackground(new Color(255, 255, 255));
        pnline1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btndashboardMouseExited

    private void btndatapelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatapelangganMouseEntered
        pndatapelanggan.setBackground(new Color(255, 255, 255));
        pnline3.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btndatapelangganMouseEntered

    private void btndatapelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatapelangganMouseExited
        pndatapelanggan.setBackground(new Color(255, 255, 255));
        pnline3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btndatapelangganMouseExited

    private void btndatasparepartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatasparepartMouseEntered
        pndatasparepart.setBackground(new Color(255, 255, 255));
        pnline4.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btndatasparepartMouseEntered

    private void btndatasparepartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatasparepartMouseExited
        pndatasparepart.setBackground(new Color(255, 255, 255));
        pnline4.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btndatasparepartMouseExited

    private void btndatakendaraanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatakendaraanMouseEntered
        pndatakendaraan.setBackground(new Color(255, 255, 255));
        pnline5.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btndatakendaraanMouseEntered

    private void btndatakendaraanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatakendaraanMouseExited
        pndatakendaraan.setBackground(new Color(255, 255, 255));
        pnline5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btndatakendaraanMouseExited

    private void btntransaksiservisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntransaksiservisMouseEntered
        pntransaksiservis.setBackground(new Color(255, 255, 255));
        pnline6.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btntransaksiservisMouseEntered

    private void btntransaksiservisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntransaksiservisMouseExited
        pntransaksiservis.setBackground(new Color(255, 255, 255));
        pnline6.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btntransaksiservisMouseExited

    private void btnlaporanservisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanservisMouseEntered
        pnlaporanservis.setBackground(new Color(255, 255, 255));
        pnline7.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btnlaporanservisMouseEntered

    private void btnlaporanservisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanservisMouseExited
        pnlaporanservis.setBackground(new Color(255, 255, 255));
        pnline7.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnlaporanservisMouseExited

    private void btnlaporantransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporantransaksiMouseEntered
        pnlaporantransaksi.setBackground(new Color(255, 255, 255));
        pnline8.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btnlaporantransaksiMouseEntered

    private void btnlaporantransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporantransaksiMouseExited
        pnlaporantransaksi.setBackground(new Color(255, 255, 255));
        pnline8.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnlaporantransaksiMouseExited

    private void btnlaporansparepartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporansparepartMouseEntered
        pnlaporansparepart.setBackground(new Color(255, 255, 255));
        pnline9.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btnlaporansparepartMouseEntered

    private void btnlaporansparepartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporansparepartMouseExited
        pnlaporansparepart.setBackground(new Color(255, 255, 255));
        pnline9.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnlaporansparepartMouseExited

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        pnlogout.setBackground(new Color(255, 255, 255));
        pnline10.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        pnlogout.setBackground(new Color(255, 255, 255));
        pnline10.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnlogoutMouseExited

    private void btndatapelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatapelangganMouseClicked
        pndatapelanggan.setBackground(new Color(250, 250, 250));
        pnline1.setBackground(new Color(25,118,210));
        
        pnutama.removeAll();
        pnutama.add(new PanelMenu.datapelanggan());
        pnutama.repaint();
        pnutama.revalidate();
    }//GEN-LAST:event_btndatapelangganMouseClicked

    private void btndatasparepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatasparepartMouseClicked
        pndatasparepart.setBackground(new Color(250, 250, 250));
        pnline1.setBackground(new Color(25,118,210));
        
        pnutama.removeAll();
        pnutama.add(new PanelMenu.datasparepart());
        pnutama.repaint();
        pnutama.revalidate();
    }//GEN-LAST:event_btndatasparepartMouseClicked

    private void btndatauserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatauserMouseClicked
        pndatauser.setBackground(new Color(250, 250, 250));
        pnline2.setBackground(new Color(25,118,210));
        
        pnutama.removeAll();
        pnutama.add(new PanelMenu.Datauser());
        pnutama.repaint();
        pnutama.revalidate();
    }//GEN-LAST:event_btndatauserMouseClicked

    private void btndatakendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatakendaraanMouseClicked
        pndatakendaraan.setBackground(new Color(250, 250, 250));
        pnline1.setBackground(new Color(25,118,210));
        
        pnutama.removeAll();
        pnutama.add(new PanelMenu.data_kendaraan());
        pnutama.repaint();
        pnutama.revalidate();
    }//GEN-LAST:event_btndatakendaraanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btndashboard;
    private javax.swing.JLabel btndatakendaraan;
    private javax.swing.JLabel btndatapelanggan;
    private javax.swing.JLabel btndatasparepart;
    private javax.swing.JLabel btndatauser;
    private javax.swing.JLabel btnlaporanservis;
    private javax.swing.JLabel btnlaporansparepart;
    private javax.swing.JLabel btnlaporantransaksi;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JLabel btntransaksiservis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pndashboard;
    private javax.swing.JPanel pndatakendaraan;
    private javax.swing.JPanel pndatapelanggan;
    private javax.swing.JPanel pndatasparepart;
    private javax.swing.JPanel pndatauser;
    private javax.swing.JPanel pnkanan;
    private javax.swing.JPanel pnkiri;
    private javax.swing.JPanel pnlaporanservis;
    private javax.swing.JPanel pnlaporansparepart;
    private javax.swing.JPanel pnlaporantransaksi;
    private javax.swing.JPanel pnline1;
    private javax.swing.JPanel pnline10;
    private javax.swing.JPanel pnline2;
    private javax.swing.JPanel pnline3;
    private javax.swing.JPanel pnline4;
    private javax.swing.JPanel pnline5;
    private javax.swing.JPanel pnline6;
    private javax.swing.JPanel pnline7;
    private javax.swing.JPanel pnline8;
    private javax.swing.JPanel pnline9;
    private javax.swing.JPanel pnlogout;
    private javax.swing.JPanel pntransaksiservis;
    private javax.swing.JPanel pnutama;
    // End of variables declaration//GEN-END:variables
}
